### ISSUE TITLE
Sorting the crmSchema.json file to prevent large differences in source control. 

### ISSUE THREAD

**Issue by mw45156** [yagasoft/DynamicsCrm-Template-based-Code-Generator-Plugin#2]
To prevent large differences between the crmSchema which is already generated and in source control and the version we're about to save, we've updated the function buttonSaveSettings_Click and buttonSaveAsSettings_Click locally, so it will sort the  crmEntityProfiles object by its EntityLogicalName. This helps us to merge the crmSchema between branches in source control. 

Could you please consider building a new version to make this possible? Thanks, see screenshot for possibile solution. 

![image](https://github.com/yagasoft/DynamicsCrm-Template-based-Code-Generator-Plugin/assets/49030093/f22c2124-2aaa-4685-b3ec-32373071944b)

**Comment by yagasoft** [comment]
@mw45156 
Thank you for your feedback and suggestion. I will indeed add it to the code as soon as possible.

**Comment by yagasoft** [comment]
@mw45156 
Done. Please check the latest version on XrmToolBox.

**Comment by vioza** [comment]
Thanks for processing!
