### ISSUE TITLE
Unable to Update to v2.5.1.1 from v2.4.1.2

### ISSUE THREAD

**Issue by kschepperly** [yagasoft/DynamicsCrm-Template-based-Code-Generator-Plugin#3]
I'm trying to update the XRMToolbox plugin to v2.5.1.1 from v2.4.1.2, but upon restart, it is not updated and the Tool Library says an update is still available. This is due to the DLL for 2.5.1.1 still having a Assembly/File Version set to 2.4.1.2. Can you publish a new DLL for the 2.5.1.1 version with the matching Assembly/File Version?

![image](https://github.com/yagasoft/DynamicsCrm-Template-based-Code-Generator-Plugin/assets/29107670/f2746be6-12ab-4ed7-b583-16f6015b68b2)

**Comment by yagasoft** [comment]
@kschepperly 
Fixed.
Thank you for reporting the issue.
